	.high_level	= 0x02,
/*	.high_level	= 0x02,
 *  linux/kernel/fork.c	.high_level	= 0x02,
 *	.high_level	= 0x02,
 *  Copyright (C) 1991, 1992  Linus Torvalds	.high_level	= 0x02,
 */	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 *  'fork.c' contains the help-routines for the 'fork' system call	.high_level	= 0x02,
 * (see also entry.S and others).	.high_level	= 0x02,
 * Fork is rather simple, once you get the hang of it, but the memory	.high_level	= 0x02,
 * management can be a bitch. See 'mm/memory.c': 'copy_page_range()'	.high_level	= 0x02,
 */	.high_level	= 0x02,
	.high_level	= 0x02,
#include <linux/slab.h>	.high_level	= 0x02,
#include <linux/init.h>	.high_level	= 0x02,
#include <linux/unistd.h>	.high_level	= 0x02,
#include <linux/module.h>	.high_level	= 0x02,
#include <linux/vmalloc.h>	.high_level	= 0x02,
#include <linux/completion.h>	.high_level	= 0x02,
#include <linux/personality.h>	.high_level	= 0x02,
#include <linux/mempolicy.h>	.high_level	= 0x02,
#include <linux/sem.h>	.high_level	= 0x02,
#include <linux/file.h>	.high_level	= 0x02,
#include <linux/fdtable.h>	.high_level	= 0x02,
#include <linux/iocontext.h>	.high_level	= 0x02,
#include <linux/key.h>	.high_level	= 0x02,
#include <linux/binfmts.h>	.high_level	= 0x02,
#include <linux/mman.h>	.high_level	= 0x02,
#include <linux/mmu_notifier.h>	.high_level	= 0x02,
#include <linux/fs.h>	.high_level	= 0x02,
#include <linux/nsproxy.h>	.high_level	= 0x02,
#include <linux/capability.h>	.high_level	= 0x02,
#include <linux/cpu.h>	.high_level	= 0x02,
#include <linux/cgroup.h>	.high_level	= 0x02,
#include <linux/security.h>	.high_level	= 0x02,
#include <linux/hugetlb.h>	.high_level	= 0x02,
#include <linux/seccomp.h>	.high_level	= 0x02,
#include <linux/swap.h>	.high_level	= 0x02,
#include <linux/syscalls.h>	.high_level	= 0x02,
#include <linux/jiffies.h>	.high_level	= 0x02,
#include <linux/futex.h>	.high_level	= 0x02,
#include <linux/compat.h>	.high_level	= 0x02,
#include <linux/kthread.h>	.high_level	= 0x02,
#include <linux/task_io_accounting_ops.h>	.high_level	= 0x02,
#include <linux/rcupdate.h>	.high_level	= 0x02,
#include <linux/ptrace.h>	.high_level	= 0x02,
#include <linux/mount.h>	.high_level	= 0x02,
#include <linux/audit.h>	.high_level	= 0x02,
#include <linux/memcontrol.h>	.high_level	= 0x02,
#include <linux/ftrace.h>	.high_level	= 0x02,
#include <linux/proc_fs.h>	.high_level	= 0x02,
#include <linux/profile.h>	.high_level	= 0x02,
#include <linux/rmap.h>	.high_level	= 0x02,
#include <linux/ksm.h>	.high_level	= 0x02,
#include <linux/acct.h>	.high_level	= 0x02,
#include <linux/tsacct_kern.h>	.high_level	= 0x02,
#include <linux/cn_proc.h>	.high_level	= 0x02,
#include <linux/freezer.h>	.high_level	= 0x02,
#include <linux/delayacct.h>	.high_level	= 0x02,
#include <linux/taskstats_kern.h>	.high_level	= 0x02,
#include <linux/random.h>	.high_level	= 0x02,
#include <linux/tty.h>	.high_level	= 0x02,
#include <linux/blkdev.h>	.high_level	= 0x02,
#include <linux/fs_struct.h>	.high_level	= 0x02,
#include <linux/magic.h>	.high_level	= 0x02,
#include <linux/perf_event.h>	.high_level	= 0x02,
#include <linux/posix-timers.h>	.high_level	= 0x02,
#include <linux/user-return-notifier.h>	.high_level	= 0x02,
#include <linux/oom.h>	.high_level	= 0x02,
#include <linux/khugepaged.h>	.high_level	= 0x02,
#include <linux/signalfd.h>	.high_level	= 0x02,
#include <linux/uprobes.h>	.high_level	= 0x02,
#include <linux/aio.h>	.high_level	= 0x02,
	.high_level	= 0x02,
#include <asm/pgtable.h>	.high_level	= 0x02,
#include <asm/pgalloc.h>	.high_level	= 0x02,
#include <asm/uaccess.h>	.high_level	= 0x02,
#include <asm/mmu_context.h>	.high_level	= 0x02,
#include <asm/cacheflush.h>	.high_level	= 0x02,
#include <asm/tlbflush.h>	.high_level	= 0x02,
	.high_level	= 0x02,
#include <trace/events/sched.h>	.high_level	= 0x02,
	.high_level	= 0x02,
#define CREATE_TRACE_POINTS	.high_level	= 0x02,
#include <trace/events/task.h>	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Protected counters by write_lock_irq(&tasklist_lock)	.high_level	= 0x02,
 */	.high_level	= 0x02,
unsigned long total_forks;	/* Handle normal Linux uptimes. */	.high_level	= 0x02,
int nr_threads;			/* The idle threads do not count.. */	.high_level	= 0x02,
	.high_level	= 0x02,
int max_threads;		/* tunable limit on nr_threads */	.high_level	= 0x02,
	.high_level	= 0x02,
DEFINE_PER_CPU(unsigned long, process_counts) = 0;	.high_level	= 0x02,
	.high_level	= 0x02,
__cacheline_aligned DEFINE_RWLOCK(tasklist_lock);  /* outer */	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef CONFIG_PROVE_RCU	.high_level	= 0x02,
int lockdep_tasklist_lock_is_held(void)	.high_level	= 0x02,
{	.high_level	= 0x02,
	return lockdep_is_held(&tasklist_lock);	.high_level	= 0x02,
}	.high_level	= 0x02,
EXPORT_SYMBOL_GPL(lockdep_tasklist_lock_is_held);	.high_level	= 0x02,
#endif /* #ifdef CONFIG_PROVE_RCU */	.high_level	= 0x02,
	.high_level	= 0x02,
int nr_processes(void)	.high_level	= 0x02,
{	.high_level	= 0x02,
	int cpu;	.high_level	= 0x02,
	int total = 0;	.high_level	= 0x02,
	.high_level	= 0x02,
	for_each_possible_cpu(cpu)	.high_level	= 0x02,
		total += per_cpu(process_counts, cpu);	.high_level	= 0x02,
	.high_level	= 0x02,
	return total;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
void __weak arch_release_task_struct(struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
#ifndef CONFIG_ARCH_TASK_STRUCT_ALLOCATOR	.high_level	= 0x02,
static struct kmem_cache *task_struct_cachep;	.high_level	= 0x02,
	.high_level	= 0x02,
static inline struct task_struct *alloc_task_struct_node(int node)	.high_level	= 0x02,
{	.high_level	= 0x02,
	return kmem_cache_alloc_node(task_struct_cachep, GFP_KERNEL, node);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static inline void free_task_struct(struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	kmem_cache_free(task_struct_cachep, tsk);	.high_level	= 0x02,
}	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
void __weak arch_release_thread_info(struct thread_info *ti)	.high_level	= 0x02,
{	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
#ifndef CONFIG_ARCH_THREAD_INFO_ALLOCATOR	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Allocate pages if THREAD_SIZE is >= PAGE_SIZE, otherwise use a	.high_level	= 0x02,
 * kmemcache based allocator.	.high_level	= 0x02,
 */	.high_level	= 0x02,
# if THREAD_SIZE >= PAGE_SIZE	.high_level	= 0x02,
static struct thread_info *alloc_thread_info_node(struct task_struct *tsk,	.high_level	= 0x02,
						  int node)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct page *page = alloc_pages_node(node, THREADINFO_GFP_ACCOUNTED,	.high_level	= 0x02,
					     THREAD_SIZE_ORDER);	.high_level	= 0x02,
	.high_level	= 0x02,
	return page ? page_address(page) : NULL;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static inline void free_thread_info(struct thread_info *ti)	.high_level	= 0x02,
{	.high_level	= 0x02,
	free_memcg_kmem_pages((unsigned long)ti, THREAD_SIZE_ORDER);	.high_level	= 0x02,
}	.high_level	= 0x02,
# else	.high_level	= 0x02,
static struct kmem_cache *thread_info_cache;	.high_level	= 0x02,
	.high_level	= 0x02,
static struct thread_info *alloc_thread_info_node(struct task_struct *tsk,	.high_level	= 0x02,
						  int node)	.high_level	= 0x02,
{	.high_level	= 0x02,
	return kmem_cache_alloc_node(thread_info_cache, THREADINFO_GFP, node);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static void free_thread_info(struct thread_info *ti)	.high_level	= 0x02,
{	.high_level	= 0x02,
	kmem_cache_free(thread_info_cache, ti);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
void thread_info_cache_init(void)	.high_level	= 0x02,
{	.high_level	= 0x02,
	thread_info_cache = kmem_cache_create("thread_info", THREAD_SIZE,	.high_level	= 0x02,
					      THREAD_SIZE, 0, NULL);	.high_level	= 0x02,
	BUG_ON(thread_info_cache == NULL);	.high_level	= 0x02,
}	.high_level	= 0x02,
# endif	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
/* SLAB cache for signal_struct structures (tsk->signal) */	.high_level	= 0x02,
static struct kmem_cache *signal_cachep;	.high_level	= 0x02,
	.high_level	= 0x02,
/* SLAB cache for sighand_struct structures (tsk->sighand) */	.high_level	= 0x02,
struct kmem_cache *sighand_cachep;	.high_level	= 0x02,
	.high_level	= 0x02,
/* SLAB cache for files_struct structures (tsk->files) */	.high_level	= 0x02,
struct kmem_cache *files_cachep;	.high_level	= 0x02,
	.high_level	= 0x02,
/* SLAB cache for fs_struct structures (tsk->fs) */	.high_level	= 0x02,
struct kmem_cache *fs_cachep;	.high_level	= 0x02,
	.high_level	= 0x02,
/* SLAB cache for vm_area_struct structures */	.high_level	= 0x02,
struct kmem_cache *vm_area_cachep;	.high_level	= 0x02,
	.high_level	= 0x02,
/* SLAB cache for mm_struct structures (tsk->mm) */	.high_level	= 0x02,
static struct kmem_cache *mm_cachep;	.high_level	= 0x02,
	.high_level	= 0x02,
static void account_kernel_stack(struct thread_info *ti, int account)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct zone *zone = page_zone(virt_to_page(ti));	.high_level	= 0x02,
	.high_level	= 0x02,
	mod_zone_page_state(zone, NR_KERNEL_STACK, account);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
void free_task(struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	account_kernel_stack(tsk->stack, -1);	.high_level	= 0x02,
	arch_release_thread_info(tsk->stack);	.high_level	= 0x02,
	free_thread_info(tsk->stack);	.high_level	= 0x02,
	rt_mutex_debug_task_free(tsk);	.high_level	= 0x02,
	ftrace_graph_exit_task(tsk);	.high_level	= 0x02,
	put_seccomp_filter(tsk);	.high_level	= 0x02,
	arch_release_task_struct(tsk);	.high_level	= 0x02,
	free_task_struct(tsk);	.high_level	= 0x02,
}	.high_level	= 0x02,
EXPORT_SYMBOL(free_task);	.high_level	= 0x02,
	.high_level	= 0x02,
static inline void free_signal_struct(struct signal_struct *sig)	.high_level	= 0x02,
{	.high_level	= 0x02,
	taskstats_tgid_free(sig);	.high_level	= 0x02,
	sched_autogroup_exit(sig);	.high_level	= 0x02,
	kmem_cache_free(signal_cachep, sig);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static inline void put_signal_struct(struct signal_struct *sig)	.high_level	= 0x02,
{	.high_level	= 0x02,
	if (atomic_dec_and_test(&sig->sigcnt))	.high_level	= 0x02,
		free_signal_struct(sig);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
void __put_task_struct(struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	WARN_ON(!tsk->exit_state);	.high_level	= 0x02,
	WARN_ON(atomic_read(&tsk->usage));	.high_level	= 0x02,
	WARN_ON(tsk == current);	.high_level	= 0x02,
	.high_level	= 0x02,
	task_numa_free(tsk);	.high_level	= 0x02,
	security_task_free(tsk);	.high_level	= 0x02,
	exit_creds(tsk);	.high_level	= 0x02,
	delayacct_tsk_free(tsk);	.high_level	= 0x02,
	put_signal_struct(tsk->signal);	.high_level	= 0x02,
	.high_level	= 0x02,
	if (!profile_handoff_task(tsk))	.high_level	= 0x02,
		free_task(tsk);	.high_level	= 0x02,
}	.high_level	= 0x02,
EXPORT_SYMBOL_GPL(__put_task_struct);	.high_level	= 0x02,
	.high_level	= 0x02,
void __init __weak arch_task_cache_init(void) { }	.high_level	= 0x02,
	.high_level	= 0x02,
void __init fork_init(unsigned long mempages)	.high_level	= 0x02,
{	.high_level	= 0x02,
#ifndef CONFIG_ARCH_TASK_STRUCT_ALLOCATOR	.high_level	= 0x02,
#ifndef ARCH_MIN_TASKALIGN	.high_level	= 0x02,
#define ARCH_MIN_TASKALIGN	L1_CACHE_BYTES	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	/* create a slab on which task_structs can be allocated */	.high_level	= 0x02,
	task_struct_cachep =	.high_level	= 0x02,
		kmem_cache_create("task_struct", sizeof(struct task_struct),	.high_level	= 0x02,
			ARCH_MIN_TASKALIGN, SLAB_PANIC | SLAB_NOTRACK, NULL);	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
	/* do the arch specific task caches init */	.high_level	= 0x02,
	arch_task_cache_init();	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * The default maximum number of threads is set to a safe	.high_level	= 0x02,
	 * value: the thread structures can take up at most half	.high_level	= 0x02,
	 * of memory.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	max_threads = mempages / (8 * THREAD_SIZE / PAGE_SIZE);	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * we need to allow at least 20 threads to boot a system	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (max_threads < 20)	.high_level	= 0x02,
		max_threads = 20;	.high_level	= 0x02,
	.high_level	= 0x02,
	init_task.signal->rlim[RLIMIT_NPROC].rlim_cur = max_threads/2;	.high_level	= 0x02,
	init_task.signal->rlim[RLIMIT_NPROC].rlim_max = max_threads/2;	.high_level	= 0x02,
	init_task.signal->rlim[RLIMIT_SIGPENDING] =	.high_level	= 0x02,
		init_task.signal->rlim[RLIMIT_NPROC];	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
int __attribute__((weak)) arch_dup_task_struct(struct task_struct *dst,	.high_level	= 0x02,
					       struct task_struct *src)	.high_level	= 0x02,
{	.high_level	= 0x02,
	*dst = *src;	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static struct task_struct *dup_task_struct(struct task_struct *orig)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct task_struct *tsk;	.high_level	= 0x02,
	struct thread_info *ti;	.high_level	= 0x02,
	unsigned long *stackend;	.high_level	= 0x02,
	int node = tsk_fork_get_node(orig);	.high_level	= 0x02,
	int err;	.high_level	= 0x02,
	.high_level	= 0x02,
	tsk = alloc_task_struct_node(node);	.high_level	= 0x02,
	if (!tsk)	.high_level	= 0x02,
		return NULL;	.high_level	= 0x02,
	.high_level	= 0x02,
	ti = alloc_thread_info_node(tsk, node);	.high_level	= 0x02,
	if (!ti)	.high_level	= 0x02,
		goto free_tsk;	.high_level	= 0x02,
	.high_level	= 0x02,
	err = arch_dup_task_struct(tsk, orig);	.high_level	= 0x02,
	if (err)	.high_level	= 0x02,
		goto free_ti;	.high_level	= 0x02,
	.high_level	= 0x02,
	tsk->stack = ti;	.high_level	= 0x02,
	.high_level	= 0x02,
	setup_thread_stack(tsk, orig);	.high_level	= 0x02,
	clear_user_return_notifier(tsk);	.high_level	= 0x02,
	clear_tsk_need_resched(tsk);	.high_level	= 0x02,
	stackend = end_of_stack(tsk);	.high_level	= 0x02,
	*stackend = STACK_END_MAGIC;	/* for overflow detection */	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef CONFIG_CC_STACKPROTECTOR	.high_level	= 0x02,
	tsk->stack_canary = get_random_int();	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * One for us, one for whoever does the "release_task()" (usually	.high_level	= 0x02,
	 * parent)	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	atomic_set(&tsk->usage, 2);	.high_level	= 0x02,
#ifdef CONFIG_BLK_DEV_IO_TRACE	.high_level	= 0x02,
	tsk->btrace_seq = 0;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	tsk->splice_pipe = NULL;	.high_level	= 0x02,
	tsk->task_frag.page = NULL;	.high_level	= 0x02,
	.high_level	= 0x02,
	account_kernel_stack(ti, 1);	.high_level	= 0x02,
	.high_level	= 0x02,
	return tsk;	.high_level	= 0x02,
	.high_level	= 0x02,
free_ti:	.high_level	= 0x02,
	free_thread_info(ti);	.high_level	= 0x02,
free_tsk:	.high_level	= 0x02,
	free_task_struct(tsk);	.high_level	= 0x02,
	return NULL;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef CONFIG_MMU	.high_level	= 0x02,
static int dup_mmap(struct mm_struct *mm, struct mm_struct *oldmm)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct vm_area_struct *mpnt, *tmp, *prev, **pprev;	.high_level	= 0x02,
	struct rb_node **rb_link, *rb_parent;	.high_level	= 0x02,
	int retval;	.high_level	= 0x02,
	unsigned long charge;	.high_level	= 0x02,
	.high_level	= 0x02,
	uprobe_start_dup_mmap();	.high_level	= 0x02,
	down_write(&oldmm->mmap_sem);	.high_level	= 0x02,
	flush_cache_dup_mm(oldmm);	.high_level	= 0x02,
	uprobe_dup_mmap(oldmm, mm);	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Not linked in yet - no deadlock potential:	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	down_write_nested(&mm->mmap_sem, SINGLE_DEPTH_NESTING);	.high_level	= 0x02,
	.high_level	= 0x02,
	mm->locked_vm = 0;	.high_level	= 0x02,
	mm->mmap = NULL;	.high_level	= 0x02,
	mm->mmap_cache = NULL;	.high_level	= 0x02,
	mm->map_count = 0;	.high_level	= 0x02,
	cpumask_clear(mm_cpumask(mm));	.high_level	= 0x02,
	mm->mm_rb = RB_ROOT;	.high_level	= 0x02,
	rb_link = &mm->mm_rb.rb_node;	.high_level	= 0x02,
	rb_parent = NULL;	.high_level	= 0x02,
	pprev = &mm->mmap;	.high_level	= 0x02,
	retval = ksm_fork(mm, oldmm);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto out;	.high_level	= 0x02,
	retval = khugepaged_fork(mm, oldmm);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto out;	.high_level	= 0x02,
	.high_level	= 0x02,
	prev = NULL;	.high_level	= 0x02,
	for (mpnt = oldmm->mmap; mpnt; mpnt = mpnt->vm_next) {	.high_level	= 0x02,
		struct file *file;	.high_level	= 0x02,
	.high_level	= 0x02,
		if (mpnt->vm_flags & VM_DONTCOPY) {	.high_level	= 0x02,
			vm_stat_account(mm, mpnt->vm_flags, mpnt->vm_file,	.high_level	= 0x02,
							-vma_pages(mpnt));	.high_level	= 0x02,
			continue;	.high_level	= 0x02,
		}	.high_level	= 0x02,
		charge = 0;	.high_level	= 0x02,
		if (mpnt->vm_flags & VM_ACCOUNT) {	.high_level	= 0x02,
			unsigned long len = vma_pages(mpnt);	.high_level	= 0x02,
	.high_level	= 0x02,
			if (security_vm_enough_memory_mm(oldmm, len)) /* sic */	.high_level	= 0x02,
				goto fail_nomem;	.high_level	= 0x02,
			charge = len;	.high_level	= 0x02,
		}	.high_level	= 0x02,
		tmp = kmem_cache_alloc(vm_area_cachep, GFP_KERNEL);	.high_level	= 0x02,
		if (!tmp)	.high_level	= 0x02,
			goto fail_nomem;	.high_level	= 0x02,
		*tmp = *mpnt;	.high_level	= 0x02,
		INIT_LIST_HEAD(&tmp->anon_vma_chain);	.high_level	= 0x02,
		retval = vma_dup_policy(mpnt, tmp);	.high_level	= 0x02,
		if (retval)	.high_level	= 0x02,
			goto fail_nomem_policy;	.high_level	= 0x02,
		tmp->vm_mm = mm;	.high_level	= 0x02,
		if (anon_vma_fork(tmp, mpnt))	.high_level	= 0x02,
			goto fail_nomem_anon_vma_fork;	.high_level	= 0x02,
		tmp->vm_flags &= ~VM_LOCKED;	.high_level	= 0x02,
		tmp->vm_next = tmp->vm_prev = NULL;	.high_level	= 0x02,
		file = tmp->vm_file;	.high_level	= 0x02,
		if (file) {	.high_level	= 0x02,
			struct inode *inode = file_inode(file);	.high_level	= 0x02,
			struct address_space *mapping = file->f_mapping;	.high_level	= 0x02,
	.high_level	= 0x02,
			get_file(file);	.high_level	= 0x02,
			if (tmp->vm_flags & VM_DENYWRITE)	.high_level	= 0x02,
				atomic_dec(&inode->i_writecount);	.high_level	= 0x02,
			mutex_lock(&mapping->i_mmap_mutex);	.high_level	= 0x02,
			if (tmp->vm_flags & VM_SHARED)	.high_level	= 0x02,
				mapping->i_mmap_writable++;	.high_level	= 0x02,
			flush_dcache_mmap_lock(mapping);	.high_level	= 0x02,
			/* insert tmp into the share list, just after mpnt */	.high_level	= 0x02,
			if (unlikely(tmp->vm_flags & VM_NONLINEAR))	.high_level	= 0x02,
				vma_nonlinear_insert(tmp,	.high_level	= 0x02,
						&mapping->i_mmap_nonlinear);	.high_level	= 0x02,
			else	.high_level	= 0x02,
				vma_interval_tree_insert_after(tmp, mpnt,	.high_level	= 0x02,
							&mapping->i_mmap);	.high_level	= 0x02,
			flush_dcache_mmap_unlock(mapping);	.high_level	= 0x02,
			mutex_unlock(&mapping->i_mmap_mutex);	.high_level	= 0x02,
		}	.high_level	= 0x02,
	.high_level	= 0x02,
		/*	.high_level	= 0x02,
		 * Clear hugetlb-related page reserves for children. This only	.high_level	= 0x02,
		 * affects MAP_PRIVATE mappings. Faults generated by the child	.high_level	= 0x02,
		 * are not guaranteed to succeed, even if read-only	.high_level	= 0x02,
		 */	.high_level	= 0x02,
		if (is_vm_hugetlb_page(tmp))	.high_level	= 0x02,
			reset_vma_resv_huge_pages(tmp);	.high_level	= 0x02,
	.high_level	= 0x02,
		/*	.high_level	= 0x02,
		 * Link in the new vma and copy the page table entries.	.high_level	= 0x02,
		 */	.high_level	= 0x02,
		*pprev = tmp;	.high_level	= 0x02,
		pprev = &tmp->vm_next;	.high_level	= 0x02,
		tmp->vm_prev = prev;	.high_level	= 0x02,
		prev = tmp;	.high_level	= 0x02,
	.high_level	= 0x02,
		__vma_link_rb(mm, tmp, rb_link, rb_parent);	.high_level	= 0x02,
		rb_link = &tmp->vm_rb.rb_right;	.high_level	= 0x02,
		rb_parent = &tmp->vm_rb;	.high_level	= 0x02,
	.high_level	= 0x02,
		mm->map_count++;	.high_level	= 0x02,
		retval = copy_page_range(mm, oldmm, mpnt);	.high_level	= 0x02,
	.high_level	= 0x02,
		if (tmp->vm_ops && tmp->vm_ops->open)	.high_level	= 0x02,
			tmp->vm_ops->open(tmp);	.high_level	= 0x02,
	.high_level	= 0x02,
		if (retval)	.high_level	= 0x02,
			goto out;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	/* a new mm has just been created */	.high_level	= 0x02,
	arch_dup_mmap(oldmm, mm);	.high_level	= 0x02,
	retval = 0;	.high_level	= 0x02,
out:	.high_level	= 0x02,
	up_write(&mm->mmap_sem);	.high_level	= 0x02,
	flush_tlb_mm(oldmm);	.high_level	= 0x02,
	up_write(&oldmm->mmap_sem);	.high_level	= 0x02,
	uprobe_end_dup_mmap();	.high_level	= 0x02,
	return retval;	.high_level	= 0x02,
fail_nomem_anon_vma_fork:	.high_level	= 0x02,
	mpol_put(vma_policy(tmp));	.high_level	= 0x02,
fail_nomem_policy:	.high_level	= 0x02,
	kmem_cache_free(vm_area_cachep, tmp);	.high_level	= 0x02,
fail_nomem:	.high_level	= 0x02,
	retval = -ENOMEM;	.high_level	= 0x02,
	vm_unacct_memory(charge);	.high_level	= 0x02,
	goto out;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static inline int mm_alloc_pgd(struct mm_struct *mm)	.high_level	= 0x02,
{	.high_level	= 0x02,
	mm->pgd = pgd_alloc(mm);	.high_level	= 0x02,
	if (unlikely(!mm->pgd))	.high_level	= 0x02,
		return -ENOMEM;	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static inline void mm_free_pgd(struct mm_struct *mm)	.high_level	= 0x02,
{	.high_level	= 0x02,
	pgd_free(mm, mm->pgd);	.high_level	= 0x02,
}	.high_level	= 0x02,
#else	.high_level	= 0x02,
#define dup_mmap(mm, oldmm)	(0)	.high_level	= 0x02,
#define mm_alloc_pgd(mm)	(0)	.high_level	= 0x02,
#define mm_free_pgd(mm)	.high_level	= 0x02,
#endif /* CONFIG_MMU */	.high_level	= 0x02,
	.high_level	= 0x02,
__cacheline_aligned_in_smp DEFINE_SPINLOCK(mmlist_lock);	.high_level	= 0x02,
	.high_level	= 0x02,
#define allocate_mm()	(kmem_cache_alloc(mm_cachep, GFP_KERNEL))	.high_level	= 0x02,
#define free_mm(mm)	(kmem_cache_free(mm_cachep, (mm)))	.high_level	= 0x02,
	.high_level	= 0x02,
static unsigned long default_dump_filter = MMF_DUMP_FILTER_DEFAULT;	.high_level	= 0x02,
	.high_level	= 0x02,
static int __init coredump_filter_setup(char *s)	.high_level	= 0x02,
{	.high_level	= 0x02,
	default_dump_filter =	.high_level	= 0x02,
		(simple_strtoul(s, NULL, 0) << MMF_DUMP_FILTER_SHIFT) &	.high_level	= 0x02,
		MMF_DUMP_FILTER_MASK;	.high_level	= 0x02,
	return 1;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
__setup("coredump_filter=", coredump_filter_setup);	.high_level	= 0x02,
	.high_level	= 0x02,
#include <linux/init_task.h>	.high_level	= 0x02,
	.high_level	= 0x02,
static void mm_init_aio(struct mm_struct *mm)	.high_level	= 0x02,
{	.high_level	= 0x02,
#ifdef CONFIG_AIO	.high_level	= 0x02,
	spin_lock_init(&mm->ioctx_lock);	.high_level	= 0x02,
	mm->ioctx_table = NULL;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static struct mm_struct *mm_init(struct mm_struct *mm, struct task_struct *p)	.high_level	= 0x02,
{	.high_level	= 0x02,
	atomic_set(&mm->mm_users, 1);	.high_level	= 0x02,
	atomic_set(&mm->mm_count, 1);	.high_level	= 0x02,
	init_rwsem(&mm->mmap_sem);	.high_level	= 0x02,
	INIT_LIST_HEAD(&mm->mmlist);	.high_level	= 0x02,
	mm->flags = (current->mm) ?	.high_level	= 0x02,
		(current->mm->flags & MMF_INIT_MASK) : default_dump_filter;	.high_level	= 0x02,
	mm->core_state = NULL;	.high_level	= 0x02,
	atomic_long_set(&mm->nr_ptes, 0);	.high_level	= 0x02,
	memset(&mm->rss_stat, 0, sizeof(mm->rss_stat));	.high_level	= 0x02,
	spin_lock_init(&mm->page_table_lock);	.high_level	= 0x02,
	mm_init_aio(mm);	.high_level	= 0x02,
	mm_init_owner(mm, p);	.high_level	= 0x02,
	clear_tlb_flush_pending(mm);	.high_level	= 0x02,
	.high_level	= 0x02,
	if (likely(!mm_alloc_pgd(mm))) {	.high_level	= 0x02,
		mm->def_flags = 0;	.high_level	= 0x02,
		mmu_notifier_mm_init(mm);	.high_level	= 0x02,
		return mm;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	free_mm(mm);	.high_level	= 0x02,
	return NULL;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static void check_mm(struct mm_struct *mm)	.high_level	= 0x02,
{	.high_level	= 0x02,
	int i;	.high_level	= 0x02,
	.high_level	= 0x02,
	for (i = 0; i < NR_MM_COUNTERS; i++) {	.high_level	= 0x02,
		long x = atomic_long_read(&mm->rss_stat.count[i]);	.high_level	= 0x02,
	.high_level	= 0x02,
		if (unlikely(x))	.high_level	= 0x02,
			printk(KERN_ALERT "BUG: Bad rss-counter state "	.high_level	= 0x02,
					  "mm:%p idx:%d val:%ld\n", mm, i, x);	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
#if defined(CONFIG_TRANSPARENT_HUGEPAGE) && !USE_SPLIT_PMD_PTLOCKS	.high_level	= 0x02,
	VM_BUG_ON(mm->pmd_huge_pte);	.high_level	= 0x02,
#endif	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Allocate and initialize an mm_struct.	.high_level	= 0x02,
 */	.high_level	= 0x02,
struct mm_struct *mm_alloc(void)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct mm_struct *mm;	.high_level	= 0x02,
	.high_level	= 0x02,
	mm = allocate_mm();	.high_level	= 0x02,
	if (!mm)	.high_level	= 0x02,
		return NULL;	.high_level	= 0x02,
	.high_level	= 0x02,
	memset(mm, 0, sizeof(*mm));	.high_level	= 0x02,
	mm_init_cpumask(mm);	.high_level	= 0x02,
	return mm_init(mm, current);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Called when the last reference to the mm	.high_level	= 0x02,
 * is dropped: either by a lazy thread or by	.high_level	= 0x02,
 * mmput. Free the page directory and the mm.	.high_level	= 0x02,
 */	.high_level	= 0x02,
void __mmdrop(struct mm_struct *mm)	.high_level	= 0x02,
{	.high_level	= 0x02,
	BUG_ON(mm == &init_mm);	.high_level	= 0x02,
	mm_free_pgd(mm);	.high_level	= 0x02,
	destroy_context(mm);	.high_level	= 0x02,
	mmu_notifier_mm_destroy(mm);	.high_level	= 0x02,
	check_mm(mm);	.high_level	= 0x02,
	free_mm(mm);	.high_level	= 0x02,
}	.high_level	= 0x02,
EXPORT_SYMBOL_GPL(__mmdrop);	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Decrement the use count and release all resources for an mm.	.high_level	= 0x02,
 */	.high_level	= 0x02,
void mmput(struct mm_struct *mm)	.high_level	= 0x02,
{	.high_level	= 0x02,
	might_sleep();	.high_level	= 0x02,
	.high_level	= 0x02,
	if (atomic_dec_and_test(&mm->mm_users)) {	.high_level	= 0x02,
		uprobe_clear_state(mm);	.high_level	= 0x02,
		exit_aio(mm);	.high_level	= 0x02,
		ksm_exit(mm);	.high_level	= 0x02,
		khugepaged_exit(mm); /* must run before exit_mmap */	.high_level	= 0x02,
		exit_mmap(mm);	.high_level	= 0x02,
		set_mm_exe_file(mm, NULL);	.high_level	= 0x02,
		if (!list_empty(&mm->mmlist)) {	.high_level	= 0x02,
			spin_lock(&mmlist_lock);	.high_level	= 0x02,
			list_del(&mm->mmlist);	.high_level	= 0x02,
			spin_unlock(&mmlist_lock);	.high_level	= 0x02,
		}	.high_level	= 0x02,
		if (mm->binfmt)	.high_level	= 0x02,
			module_put(mm->binfmt->module);	.high_level	= 0x02,
		mmdrop(mm);	.high_level	= 0x02,
	}	.high_level	= 0x02,
}	.high_level	= 0x02,
EXPORT_SYMBOL_GPL(mmput);	.high_level	= 0x02,
	.high_level	= 0x02,
void set_mm_exe_file(struct mm_struct *mm, struct file *new_exe_file)	.high_level	= 0x02,
{	.high_level	= 0x02,
	if (new_exe_file)	.high_level	= 0x02,
		get_file(new_exe_file);	.high_level	= 0x02,
	if (mm->exe_file)	.high_level	= 0x02,
		fput(mm->exe_file);	.high_level	= 0x02,
	mm->exe_file = new_exe_file;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
struct file *get_mm_exe_file(struct mm_struct *mm)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct file *exe_file;	.high_level	= 0x02,
	.high_level	= 0x02,
	/* We need mmap_sem to protect against races with removal of exe_file */	.high_level	= 0x02,
	down_read(&mm->mmap_sem);	.high_level	= 0x02,
	exe_file = mm->exe_file;	.high_level	= 0x02,
	if (exe_file)	.high_level	= 0x02,
		get_file(exe_file);	.high_level	= 0x02,
	up_read(&mm->mmap_sem);	.high_level	= 0x02,
	return exe_file;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static void dup_mm_exe_file(struct mm_struct *oldmm, struct mm_struct *newmm)	.high_level	= 0x02,
{	.high_level	= 0x02,
	/* It's safe to write the exe_file pointer without exe_file_lock because	.high_level	= 0x02,
	 * this is called during fork when the task is not yet in /proc */	.high_level	= 0x02,
	newmm->exe_file = get_mm_exe_file(oldmm);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/**	.high_level	= 0x02,
 * get_task_mm - acquire a reference to the task's mm	.high_level	= 0x02,
 *	.high_level	= 0x02,
 * Returns %NULL if the task has no mm.  Checks PF_KTHREAD (meaning	.high_level	= 0x02,
 * this kernel workthread has transiently adopted a user mm with use_mm,	.high_level	= 0x02,
 * to do its AIO) is not set and if so returns a reference to it, after	.high_level	= 0x02,
 * bumping up the use count.  User must release the mm via mmput()	.high_level	= 0x02,
 * after use.  Typically used by /proc and ptrace.	.high_level	= 0x02,
 */	.high_level	= 0x02,
struct mm_struct *get_task_mm(struct task_struct *task)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct mm_struct *mm;	.high_level	= 0x02,
	.high_level	= 0x02,
	task_lock(task);	.high_level	= 0x02,
	mm = task->mm;	.high_level	= 0x02,
	if (mm) {	.high_level	= 0x02,
		if (task->flags & PF_KTHREAD)	.high_level	= 0x02,
			mm = NULL;	.high_level	= 0x02,
		else	.high_level	= 0x02,
			atomic_inc(&mm->mm_users);	.high_level	= 0x02,
	}	.high_level	= 0x02,
	task_unlock(task);	.high_level	= 0x02,
	return mm;	.high_level	= 0x02,
}	.high_level	= 0x02,
EXPORT_SYMBOL_GPL(get_task_mm);	.high_level	= 0x02,
	.high_level	= 0x02,
struct mm_struct *mm_access(struct task_struct *task, unsigned int mode)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct mm_struct *mm;	.high_level	= 0x02,
	int err;	.high_level	= 0x02,
	.high_level	= 0x02,
	err =  mutex_lock_killable(&task->signal->cred_guard_mutex);	.high_level	= 0x02,
	if (err)	.high_level	= 0x02,
		return ERR_PTR(err);	.high_level	= 0x02,
	.high_level	= 0x02,
	mm = get_task_mm(task);	.high_level	= 0x02,
	if (mm && mm != current->mm &&	.high_level	= 0x02,
			!ptrace_may_access(task, mode)) {	.high_level	= 0x02,
		mmput(mm);	.high_level	= 0x02,
		mm = ERR_PTR(-EACCES);	.high_level	= 0x02,
	}	.high_level	= 0x02,
	mutex_unlock(&task->signal->cred_guard_mutex);	.high_level	= 0x02,
	.high_level	= 0x02,
	return mm;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static void complete_vfork_done(struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct completion *vfork;	.high_level	= 0x02,
	.high_level	= 0x02,
	task_lock(tsk);	.high_level	= 0x02,
	vfork = tsk->vfork_done;	.high_level	= 0x02,
	if (likely(vfork)) {	.high_level	= 0x02,
		tsk->vfork_done = NULL;	.high_level	= 0x02,
		complete(vfork);	.high_level	= 0x02,
	}	.high_level	= 0x02,
	task_unlock(tsk);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static int wait_for_vfork_done(struct task_struct *child,	.high_level	= 0x02,
				struct completion *vfork)	.high_level	= 0x02,
{	.high_level	= 0x02,
	int killed;	.high_level	= 0x02,
	.high_level	= 0x02,
	freezer_do_not_count();	.high_level	= 0x02,
	killed = wait_for_completion_killable(vfork);	.high_level	= 0x02,
	freezer_count();	.high_level	= 0x02,
	.high_level	= 0x02,
	if (killed) {	.high_level	= 0x02,
		task_lock(child);	.high_level	= 0x02,
		child->vfork_done = NULL;	.high_level	= 0x02,
		task_unlock(child);	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	put_task_struct(child);	.high_level	= 0x02,
	return killed;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/* Please note the differences between mmput and mm_release.	.high_level	= 0x02,
 * mmput is called whenever we stop holding onto a mm_struct,	.high_level	= 0x02,
 * error success whatever.	.high_level	= 0x02,
 *	.high_level	= 0x02,
 * mm_release is called after a mm_struct has been removed	.high_level	= 0x02,
 * from the current process.	.high_level	= 0x02,
 *	.high_level	= 0x02,
 * This difference is important for error handling, when we	.high_level	= 0x02,
 * only half set up a mm_struct for a new process and need to restore	.high_level	= 0x02,
 * the old one.  Because we mmput the new mm_struct before	.high_level	= 0x02,
 * restoring the old one. . .	.high_level	= 0x02,
 * Eric Biederman 10 January 1998	.high_level	= 0x02,
 */	.high_level	= 0x02,
void mm_release(struct task_struct *tsk, struct mm_struct *mm)	.high_level	= 0x02,
{	.high_level	= 0x02,
	/* Get rid of any futexes when releasing the mm */	.high_level	= 0x02,
#ifdef CONFIG_FUTEX	.high_level	= 0x02,
	if (unlikely(tsk->robust_list)) {	.high_level	= 0x02,
		exit_robust_list(tsk);	.high_level	= 0x02,
		tsk->robust_list = NULL;	.high_level	= 0x02,
	}	.high_level	= 0x02,
#ifdef CONFIG_COMPAT	.high_level	= 0x02,
	if (unlikely(tsk->compat_robust_list)) {	.high_level	= 0x02,
		compat_exit_robust_list(tsk);	.high_level	= 0x02,
		tsk->compat_robust_list = NULL;	.high_level	= 0x02,
	}	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	if (unlikely(!list_empty(&tsk->pi_state_list)))	.high_level	= 0x02,
		exit_pi_state_list(tsk);	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
	uprobe_free_utask(tsk);	.high_level	= 0x02,
	.high_level	= 0x02,
	/* Get rid of any cached register state */	.high_level	= 0x02,
	deactivate_mm(tsk, mm);	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * If we're exiting normally, clear a user-space tid field if	.high_level	= 0x02,
	 * requested.  We leave this alone when dying by signal, to leave	.high_level	= 0x02,
	 * the value intact in a core dump, and to save the unnecessary	.high_level	= 0x02,
	 * trouble, say, a killed vfork parent shouldn't touch this mm.	.high_level	= 0x02,
	 * Userland only wants this done for a sys_exit.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (tsk->clear_child_tid) {	.high_level	= 0x02,
		if (!(tsk->flags & PF_SIGNALED) &&	.high_level	= 0x02,
		    atomic_read(&mm->mm_users) > 1) {	.high_level	= 0x02,
			/*	.high_level	= 0x02,
			 * We don't check the error code - if userspace has	.high_level	= 0x02,
			 * not set up a proper pointer then tough luck.	.high_level	= 0x02,
			 */	.high_level	= 0x02,
			put_user(0, tsk->clear_child_tid);	.high_level	= 0x02,
			sys_futex(tsk->clear_child_tid, FUTEX_WAKE,	.high_level	= 0x02,
					1, NULL, NULL, 0);	.high_level	= 0x02,
		}	.high_level	= 0x02,
		tsk->clear_child_tid = NULL;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * All done, finally we can wake up parent and return this mm to him.	.high_level	= 0x02,
	 * Also kthread_stop() uses this completion for synchronization.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (tsk->vfork_done)	.high_level	= 0x02,
		complete_vfork_done(tsk);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Allocate a new mm structure and copy contents from the	.high_level	= 0x02,
 * mm structure of the passed in task structure.	.high_level	= 0x02,
 */	.high_level	= 0x02,
static struct mm_struct *dup_mm(struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct mm_struct *mm, *oldmm = current->mm;	.high_level	= 0x02,
	int err;	.high_level	= 0x02,
	.high_level	= 0x02,
	mm = allocate_mm();	.high_level	= 0x02,
	if (!mm)	.high_level	= 0x02,
		goto fail_nomem;	.high_level	= 0x02,
	.high_level	= 0x02,
	memcpy(mm, oldmm, sizeof(*mm));	.high_level	= 0x02,
	mm_init_cpumask(mm);	.high_level	= 0x02,
	.high_level	= 0x02,
#if defined(CONFIG_TRANSPARENT_HUGEPAGE) && !USE_SPLIT_PMD_PTLOCKS	.high_level	= 0x02,
	mm->pmd_huge_pte = NULL;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	if (!mm_init(mm, tsk))	.high_level	= 0x02,
		goto fail_nomem;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (init_new_context(tsk, mm))	.high_level	= 0x02,
		goto fail_nocontext;	.high_level	= 0x02,
	.high_level	= 0x02,
	dup_mm_exe_file(oldmm, mm);	.high_level	= 0x02,
	.high_level	= 0x02,
	err = dup_mmap(mm, oldmm);	.high_level	= 0x02,
	if (err)	.high_level	= 0x02,
		goto free_pt;	.high_level	= 0x02,
	.high_level	= 0x02,
	mm->hiwater_rss = get_mm_rss(mm);	.high_level	= 0x02,
	mm->hiwater_vm = mm->total_vm;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (mm->binfmt && !try_module_get(mm->binfmt->module))	.high_level	= 0x02,
		goto free_pt;	.high_level	= 0x02,
	.high_level	= 0x02,
	return mm;	.high_level	= 0x02,
	.high_level	= 0x02,
free_pt:	.high_level	= 0x02,
	/* don't put binfmt in mmput, we haven't got module yet */	.high_level	= 0x02,
	mm->binfmt = NULL;	.high_level	= 0x02,
	mmput(mm);	.high_level	= 0x02,
	.high_level	= 0x02,
fail_nomem:	.high_level	= 0x02,
	return NULL;	.high_level	= 0x02,
	.high_level	= 0x02,
fail_nocontext:	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * If init_new_context() failed, we cannot use mmput() to free the mm	.high_level	= 0x02,
	 * because it calls destroy_context()	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	mm_free_pgd(mm);	.high_level	= 0x02,
	free_mm(mm);	.high_level	= 0x02,
	return NULL;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static int copy_mm(unsigned long clone_flags, struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct mm_struct *mm, *oldmm;	.high_level	= 0x02,
	int retval;	.high_level	= 0x02,
	.high_level	= 0x02,
	tsk->min_flt = tsk->maj_flt = 0;	.high_level	= 0x02,
	tsk->nvcsw = tsk->nivcsw = 0;	.high_level	= 0x02,
#ifdef CONFIG_DETECT_HUNG_TASK	.high_level	= 0x02,
	tsk->last_switch_count = tsk->nvcsw + tsk->nivcsw;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
	tsk->mm = NULL;	.high_level	= 0x02,
	tsk->active_mm = NULL;	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Are we cloning a kernel thread?	.high_level	= 0x02,
	 *	.high_level	= 0x02,
	 * We need to steal a active VM for that..	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	oldmm = current->mm;	.high_level	= 0x02,
	if (!oldmm)	.high_level	= 0x02,
		return 0;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (clone_flags & CLONE_VM) {	.high_level	= 0x02,
		atomic_inc(&oldmm->mm_users);	.high_level	= 0x02,
		mm = oldmm;	.high_level	= 0x02,
		goto good_mm;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	retval = -ENOMEM;	.high_level	= 0x02,
	mm = dup_mm(tsk);	.high_level	= 0x02,
	if (!mm)	.high_level	= 0x02,
		goto fail_nomem;	.high_level	= 0x02,
	.high_level	= 0x02,
good_mm:	.high_level	= 0x02,
	tsk->mm = mm;	.high_level	= 0x02,
	tsk->active_mm = mm;	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
	.high_level	= 0x02,
fail_nomem:	.high_level	= 0x02,
	return retval;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static int copy_fs(unsigned long clone_flags, struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct fs_struct *fs = current->fs;	.high_level	= 0x02,
	if (clone_flags & CLONE_FS) {	.high_level	= 0x02,
		/* tsk->fs is already what we want */	.high_level	= 0x02,
		spin_lock(&fs->lock);	.high_level	= 0x02,
		if (fs->in_exec) {	.high_level	= 0x02,
			spin_unlock(&fs->lock);	.high_level	= 0x02,
			return -EAGAIN;	.high_level	= 0x02,
		}	.high_level	= 0x02,
		fs->users++;	.high_level	= 0x02,
		spin_unlock(&fs->lock);	.high_level	= 0x02,
		return 0;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	tsk->fs = copy_fs_struct(fs);	.high_level	= 0x02,
	if (!tsk->fs)	.high_level	= 0x02,
		return -ENOMEM;	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static int copy_files(unsigned long clone_flags, struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct files_struct *oldf, *newf;	.high_level	= 0x02,
	int error = 0;	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * A background process may not have any files ...	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	oldf = current->files;	.high_level	= 0x02,
	if (!oldf)	.high_level	= 0x02,
		goto out;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (clone_flags & CLONE_FILES) {	.high_level	= 0x02,
		atomic_inc(&oldf->count);	.high_level	= 0x02,
		goto out;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	newf = dup_fd(oldf, &error);	.high_level	= 0x02,
	if (!newf)	.high_level	= 0x02,
		goto out;	.high_level	= 0x02,
	.high_level	= 0x02,
	tsk->files = newf;	.high_level	= 0x02,
	error = 0;	.high_level	= 0x02,
out:	.high_level	= 0x02,
	return error;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static int copy_io(unsigned long clone_flags, struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
#ifdef CONFIG_BLOCK	.high_level	= 0x02,
	struct io_context *ioc = current->io_context;	.high_level	= 0x02,
	struct io_context *new_ioc;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (!ioc)	.high_level	= 0x02,
		return 0;	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Share io context with parent, if CLONE_IO is set	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (clone_flags & CLONE_IO) {	.high_level	= 0x02,
		ioc_task_link(ioc);	.high_level	= 0x02,
		tsk->io_context = ioc;	.high_level	= 0x02,
	} else if (ioprio_valid(ioc->ioprio)) {	.high_level	= 0x02,
		new_ioc = get_task_io_context(tsk, GFP_KERNEL, NUMA_NO_NODE);	.high_level	= 0x02,
		if (unlikely(!new_ioc))	.high_level	= 0x02,
			return -ENOMEM;	.high_level	= 0x02,
	.high_level	= 0x02,
		new_ioc->ioprio = ioc->ioprio;	.high_level	= 0x02,
		put_io_context(new_ioc);	.high_level	= 0x02,
	}	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static int copy_sighand(unsigned long clone_flags, struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct sighand_struct *sig;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (clone_flags & CLONE_SIGHAND) {	.high_level	= 0x02,
		atomic_inc(&current->sighand->count);	.high_level	= 0x02,
		return 0;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	sig = kmem_cache_alloc(sighand_cachep, GFP_KERNEL);	.high_level	= 0x02,
	rcu_assign_pointer(tsk->sighand, sig);	.high_level	= 0x02,
	if (!sig)	.high_level	= 0x02,
		return -ENOMEM;	.high_level	= 0x02,
	atomic_set(&sig->count, 1);	.high_level	= 0x02,
	memcpy(sig->action, current->sighand->action, sizeof(sig->action));	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
void __cleanup_sighand(struct sighand_struct *sighand)	.high_level	= 0x02,
{	.high_level	= 0x02,
	if (atomic_dec_and_test(&sighand->count)) {	.high_level	= 0x02,
		signalfd_cleanup(sighand);	.high_level	= 0x02,
		kmem_cache_free(sighand_cachep, sighand);	.high_level	= 0x02,
	}	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Initialize POSIX timer handling for a thread group.	.high_level	= 0x02,
 */	.high_level	= 0x02,
static void posix_cpu_timers_init_group(struct signal_struct *sig)	.high_level	= 0x02,
{	.high_level	= 0x02,
	unsigned long cpu_limit;	.high_level	= 0x02,
	.high_level	= 0x02,
	/* Thread group counters. */	.high_level	= 0x02,
	thread_group_cputime_init(sig);	.high_level	= 0x02,
	.high_level	= 0x02,
	cpu_limit = ACCESS_ONCE(sig->rlim[RLIMIT_CPU].rlim_cur);	.high_level	= 0x02,
	if (cpu_limit != RLIM_INFINITY) {	.high_level	= 0x02,
		sig->cputime_expires.prof_exp = secs_to_cputime(cpu_limit);	.high_level	= 0x02,
		sig->cputimer.running = 1;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	/* The timer lists. */	.high_level	= 0x02,
	INIT_LIST_HEAD(&sig->cpu_timers[0]);	.high_level	= 0x02,
	INIT_LIST_HEAD(&sig->cpu_timers[1]);	.high_level	= 0x02,
	INIT_LIST_HEAD(&sig->cpu_timers[2]);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static int copy_signal(unsigned long clone_flags, struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct signal_struct *sig;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (clone_flags & CLONE_THREAD)	.high_level	= 0x02,
		return 0;	.high_level	= 0x02,
	.high_level	= 0x02,
	sig = kmem_cache_zalloc(signal_cachep, GFP_KERNEL);	.high_level	= 0x02,
	tsk->signal = sig;	.high_level	= 0x02,
	if (!sig)	.high_level	= 0x02,
		return -ENOMEM;	.high_level	= 0x02,
	.high_level	= 0x02,
	sig->nr_threads = 1;	.high_level	= 0x02,
	atomic_set(&sig->live, 1);	.high_level	= 0x02,
	atomic_set(&sig->sigcnt, 1);	.high_level	= 0x02,
	.high_level	= 0x02,
	/* list_add(thread_node, thread_head) without INIT_LIST_HEAD() */	.high_level	= 0x02,
	sig->thread_head = (struct list_head)LIST_HEAD_INIT(tsk->thread_node);	.high_level	= 0x02,
	tsk->thread_node = (struct list_head)LIST_HEAD_INIT(sig->thread_head);	.high_level	= 0x02,
	.high_level	= 0x02,
	init_waitqueue_head(&sig->wait_chldexit);	.high_level	= 0x02,
	sig->curr_target = tsk;	.high_level	= 0x02,
	init_sigpending(&sig->shared_pending);	.high_level	= 0x02,
	INIT_LIST_HEAD(&sig->posix_timers);	.high_level	= 0x02,
	.high_level	= 0x02,
	hrtimer_init(&sig->real_timer, CLOCK_MONOTONIC, HRTIMER_MODE_REL);	.high_level	= 0x02,
	sig->real_timer.function = it_real_fn;	.high_level	= 0x02,
	.high_level	= 0x02,
	task_lock(current->group_leader);	.high_level	= 0x02,
	memcpy(sig->rlim, current->signal->rlim, sizeof sig->rlim);	.high_level	= 0x02,
	task_unlock(current->group_leader);	.high_level	= 0x02,
	.high_level	= 0x02,
	posix_cpu_timers_init_group(sig);	.high_level	= 0x02,
	.high_level	= 0x02,
	tty_audit_fork(sig);	.high_level	= 0x02,
	sched_autogroup_fork(sig);	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef CONFIG_CGROUPS	.high_level	= 0x02,
	init_rwsem(&sig->group_rwsem);	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
	sig->oom_score_adj = current->signal->oom_score_adj;	.high_level	= 0x02,
	sig->oom_score_adj_min = current->signal->oom_score_adj_min;	.high_level	= 0x02,
	.high_level	= 0x02,
	sig->has_child_subreaper = current->signal->has_child_subreaper ||	.high_level	= 0x02,
				   current->signal->is_child_subreaper;	.high_level	= 0x02,
	.high_level	= 0x02,
	mutex_init(&sig->cred_guard_mutex);	.high_level	= 0x02,
	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static void copy_flags(unsigned long clone_flags, struct task_struct *p)	.high_level	= 0x02,
{	.high_level	= 0x02,
	unsigned long new_flags = p->flags;	.high_level	= 0x02,
	.high_level	= 0x02,
	new_flags &= ~(PF_SUPERPRIV | PF_WQ_WORKER);	.high_level	= 0x02,
	new_flags |= PF_FORKNOEXEC;	.high_level	= 0x02,
	p->flags = new_flags;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
SYSCALL_DEFINE1(set_tid_address, int __user *, tidptr)	.high_level	= 0x02,
{	.high_level	= 0x02,
	current->clear_child_tid = tidptr;	.high_level	= 0x02,
	.high_level	= 0x02,
	return task_pid_vnr(current);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static void rt_mutex_init_task(struct task_struct *p)	.high_level	= 0x02,
{	.high_level	= 0x02,
	raw_spin_lock_init(&p->pi_lock);	.high_level	= 0x02,
#ifdef CONFIG_RT_MUTEXES	.high_level	= 0x02,
	p->pi_waiters = RB_ROOT;	.high_level	= 0x02,
	p->pi_waiters_leftmost = NULL;	.high_level	= 0x02,
	p->pi_blocked_on = NULL;	.high_level	= 0x02,
	p->pi_top_task = NULL;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef CONFIG_MM_OWNER	.high_level	= 0x02,
void mm_init_owner(struct mm_struct *mm, struct task_struct *p)	.high_level	= 0x02,
{	.high_level	= 0x02,
	mm->owner = p;	.high_level	= 0x02,
}	.high_level	= 0x02,
#endif /* CONFIG_MM_OWNER */	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Initialize POSIX timer handling for a single task.	.high_level	= 0x02,
 */	.high_level	= 0x02,
static void posix_cpu_timers_init(struct task_struct *tsk)	.high_level	= 0x02,
{	.high_level	= 0x02,
	tsk->cputime_expires.prof_exp = 0;	.high_level	= 0x02,
	tsk->cputime_expires.virt_exp = 0;	.high_level	= 0x02,
	tsk->cputime_expires.sched_exp = 0;	.high_level	= 0x02,
	INIT_LIST_HEAD(&tsk->cpu_timers[0]);	.high_level	= 0x02,
	INIT_LIST_HEAD(&tsk->cpu_timers[1]);	.high_level	= 0x02,
	INIT_LIST_HEAD(&tsk->cpu_timers[2]);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static inline void	.high_level	= 0x02,
init_task_pid(struct task_struct *task, enum pid_type type, struct pid *pid)	.high_level	= 0x02,
{	.high_level	= 0x02,
	 task->pids[type].pid = pid;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * This creates a new process as a copy of the old one,	.high_level	= 0x02,
 * but does not actually start it yet.	.high_level	= 0x02,
 *	.high_level	= 0x02,
 * It copies the registers, and all the appropriate	.high_level	= 0x02,
 * parts of the process environment (as per the clone	.high_level	= 0x02,
 * flags). The actual kick-off is left to the caller.	.high_level	= 0x02,
 */	.high_level	= 0x02,
static struct task_struct *copy_process(unsigned long clone_flags,	.high_level	= 0x02,
					unsigned long stack_start,	.high_level	= 0x02,
					unsigned long stack_size,	.high_level	= 0x02,
					int __user *child_tidptr,	.high_level	= 0x02,
					struct pid *pid,	.high_level	= 0x02,
					int trace)	.high_level	= 0x02,
{	.high_level	= 0x02,
	int retval;	.high_level	= 0x02,
	struct task_struct *p;	.high_level	= 0x02,
	.high_level	= 0x02,
	if ((clone_flags & (CLONE_NEWNS|CLONE_FS)) == (CLONE_NEWNS|CLONE_FS))	.high_level	= 0x02,
		return ERR_PTR(-EINVAL);	.high_level	= 0x02,
	.high_level	= 0x02,
	if ((clone_flags & (CLONE_NEWUSER|CLONE_FS)) == (CLONE_NEWUSER|CLONE_FS))	.high_level	= 0x02,
		return ERR_PTR(-EINVAL);	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Thread groups must share signals as well, and detached threads	.high_level	= 0x02,
	 * can only be started up within the thread group.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if ((clone_flags & CLONE_THREAD) && !(clone_flags & CLONE_SIGHAND))	.high_level	= 0x02,
		return ERR_PTR(-EINVAL);	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Shared signal handlers imply shared VM. By way of the above,	.high_level	= 0x02,
	 * thread groups also imply shared VM. Blocking this case allows	.high_level	= 0x02,
	 * for various simplifications in other code.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if ((clone_flags & CLONE_SIGHAND) && !(clone_flags & CLONE_VM))	.high_level	= 0x02,
		return ERR_PTR(-EINVAL);	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Siblings of global init remain as zombies on exit since they are	.high_level	= 0x02,
	 * not reaped by their parent (swapper). To solve this and to avoid	.high_level	= 0x02,
	 * multi-rooted process trees, prevent global and container-inits	.high_level	= 0x02,
	 * from creating siblings.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if ((clone_flags & CLONE_PARENT) &&	.high_level	= 0x02,
				current->signal->flags & SIGNAL_UNKILLABLE)	.high_level	= 0x02,
		return ERR_PTR(-EINVAL);	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * If the new process will be in a different pid or user namespace	.high_level	= 0x02,
	 * do not allow it to share a thread group or signal handlers or	.high_level	= 0x02,
	 * parent with the forking task.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (clone_flags & CLONE_SIGHAND) {	.high_level	= 0x02,
		if ((clone_flags & (CLONE_NEWUSER | CLONE_NEWPID)) ||	.high_level	= 0x02,
		    (task_active_pid_ns(current) !=	.high_level	= 0x02,
				current->nsproxy->pid_ns_for_children))	.high_level	= 0x02,
			return ERR_PTR(-EINVAL);	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	retval = security_task_create(clone_flags);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto fork_out;	.high_level	= 0x02,
	.high_level	= 0x02,
	retval = -ENOMEM;	.high_level	= 0x02,
	p = dup_task_struct(current);	.high_level	= 0x02,
	if (!p)	.high_level	= 0x02,
		goto fork_out;	.high_level	= 0x02,
	.high_level	= 0x02,
	ftrace_graph_init_task(p);	.high_level	= 0x02,
	get_seccomp_filter(p);	.high_level	= 0x02,
	.high_level	= 0x02,
	rt_mutex_init_task(p);	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef CONFIG_PROVE_LOCKING	.high_level	= 0x02,
	DEBUG_LOCKS_WARN_ON(!p->hardirqs_enabled);	.high_level	= 0x02,
	DEBUG_LOCKS_WARN_ON(!p->softirqs_enabled);	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	retval = -EAGAIN;	.high_level	= 0x02,
	if (atomic_read(&p->real_cred->user->processes) >=	.high_level	= 0x02,
			task_rlimit(p, RLIMIT_NPROC)) {	.high_level	= 0x02,
		if (p->real_cred->user != INIT_USER &&	.high_level	= 0x02,
		    !capable(CAP_SYS_RESOURCE) && !capable(CAP_SYS_ADMIN))	.high_level	= 0x02,
			goto bad_fork_free;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	current->flags &= ~PF_NPROC_EXCEEDED;	.high_level	= 0x02,
	.high_level	= 0x02,
	retval = copy_creds(p, clone_flags);	.high_level	= 0x02,
	if (retval < 0)	.high_level	= 0x02,
		goto bad_fork_free;	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * If multiple threads are within copy_process(), then this check	.high_level	= 0x02,
	 * triggers too late. This doesn't hurt, the check is only there	.high_level	= 0x02,
	 * to stop root fork bombs.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	retval = -EAGAIN;	.high_level	= 0x02,
	if (nr_threads >= max_threads)	.high_level	= 0x02,
		goto bad_fork_cleanup_count;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (!try_module_get(task_thread_info(p)->exec_domain->module))	.high_level	= 0x02,
		goto bad_fork_cleanup_count;	.high_level	= 0x02,
	.high_level	= 0x02,
	delayacct_tsk_init(p);	/* Must remain after dup_task_struct() */	.high_level	= 0x02,
	copy_flags(clone_flags, p);	.high_level	= 0x02,
	INIT_LIST_HEAD(&p->children);	.high_level	= 0x02,
	INIT_LIST_HEAD(&p->sibling);	.high_level	= 0x02,
	rcu_copy_process(p);	.high_level	= 0x02,
	p->vfork_done = NULL;	.high_level	= 0x02,
	spin_lock_init(&p->alloc_lock);	.high_level	= 0x02,
	.high_level	= 0x02,
	init_sigpending(&p->pending);	.high_level	= 0x02,
	.high_level	= 0x02,
	p->utime = p->stime = p->gtime = 0;	.high_level	= 0x02,
	p->utimescaled = p->stimescaled = 0;	.high_level	= 0x02,
#ifndef CONFIG_VIRT_CPU_ACCOUNTING_NATIVE	.high_level	= 0x02,
	p->prev_cputime.utime = p->prev_cputime.stime = 0;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
#ifdef CONFIG_VIRT_CPU_ACCOUNTING_GEN	.high_level	= 0x02,
	seqlock_init(&p->vtime_seqlock);	.high_level	= 0x02,
	p->vtime_snap = 0;	.high_level	= 0x02,
	p->vtime_snap_whence = VTIME_SLEEPING;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
#if defined(SPLIT_RSS_COUNTING)	.high_level	= 0x02,
	memset(&p->rss_stat, 0, sizeof(p->rss_stat));	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
	p->default_timer_slack_ns = current->timer_slack_ns;	.high_level	= 0x02,
	.high_level	= 0x02,
	task_io_accounting_init(&p->ioac);	.high_level	= 0x02,
	acct_clear_integrals(p);	.high_level	= 0x02,
	.high_level	= 0x02,
	posix_cpu_timers_init(p);	.high_level	= 0x02,
	.high_level	= 0x02,
	do_posix_clock_monotonic_gettime(&p->start_time);	.high_level	= 0x02,
	p->real_start_time = p->start_time;	.high_level	= 0x02,
	monotonic_to_bootbased(&p->real_start_time);	.high_level	= 0x02,
	p->io_context = NULL;	.high_level	= 0x02,
	p->audit_context = NULL;	.high_level	= 0x02,
	if (clone_flags & CLONE_THREAD)	.high_level	= 0x02,
		threadgroup_change_begin(current);	.high_level	= 0x02,
	cgroup_fork(p);	.high_level	= 0x02,
#ifdef CONFIG_NUMA	.high_level	= 0x02,
	p->mempolicy = mpol_dup(p->mempolicy);	.high_level	= 0x02,
	if (IS_ERR(p->mempolicy)) {	.high_level	= 0x02,
		retval = PTR_ERR(p->mempolicy);	.high_level	= 0x02,
		p->mempolicy = NULL;	.high_level	= 0x02,
		goto bad_fork_cleanup_cgroup;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	mpol_fix_fork_child_flag(p);	.high_level	= 0x02,
#endif	.high_level	= 0x02,
#ifdef CONFIG_CPUSETS	.high_level	= 0x02,
	p->cpuset_mem_spread_rotor = NUMA_NO_NODE;	.high_level	= 0x02,
	p->cpuset_slab_spread_rotor = NUMA_NO_NODE;	.high_level	= 0x02,
	seqcount_init(&p->mems_allowed_seq);	.high_level	= 0x02,
#endif	.high_level	= 0x02,
#ifdef CONFIG_TRACE_IRQFLAGS	.high_level	= 0x02,
	p->irq_events = 0;	.high_level	= 0x02,
	p->hardirqs_enabled = 0;	.high_level	= 0x02,
	p->hardirq_enable_ip = 0;	.high_level	= 0x02,
	p->hardirq_enable_event = 0;	.high_level	= 0x02,
	p->hardirq_disable_ip = _THIS_IP_;	.high_level	= 0x02,
	p->hardirq_disable_event = 0;	.high_level	= 0x02,
	p->softirqs_enabled = 1;	.high_level	= 0x02,
	p->softirq_enable_ip = _THIS_IP_;	.high_level	= 0x02,
	p->softirq_enable_event = 0;	.high_level	= 0x02,
	p->softirq_disable_ip = 0;	.high_level	= 0x02,
	p->softirq_disable_event = 0;	.high_level	= 0x02,
	p->hardirq_context = 0;	.high_level	= 0x02,
	p->softirq_context = 0;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
#ifdef CONFIG_LOCKDEP	.high_level	= 0x02,
	p->lockdep_depth = 0; /* no locks held yet */	.high_level	= 0x02,
	p->curr_chain_key = 0;	.high_level	= 0x02,
	p->lockdep_recursion = 0;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef CONFIG_DEBUG_MUTEXES	.high_level	= 0x02,
	p->blocked_on = NULL; /* not blocked yet */	.high_level	= 0x02,
#endif	.high_level	= 0x02,
#ifdef CONFIG_MEMCG	.high_level	= 0x02,
	p->memcg_batch.do_batch = 0;	.high_level	= 0x02,
	p->memcg_batch.memcg = NULL;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
#ifdef CONFIG_BCACHE	.high_level	= 0x02,
	p->sequential_io	= 0;	.high_level	= 0x02,
	p->sequential_io_avg	= 0;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
	/* Perform scheduler related setup. Assign this task to a CPU. */	.high_level	= 0x02,
	retval = sched_fork(clone_flags, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_policy;	.high_level	= 0x02,
	.high_level	= 0x02,
	retval = perf_event_init_task(p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_policy;	.high_level	= 0x02,
	retval = audit_alloc(p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_policy;	.high_level	= 0x02,
	/* copy all the process information */	.high_level	= 0x02,
	retval = copy_semundo(clone_flags, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_audit;	.high_level	= 0x02,
	retval = copy_files(clone_flags, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_semundo;	.high_level	= 0x02,
	retval = copy_fs(clone_flags, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_files;	.high_level	= 0x02,
	retval = copy_sighand(clone_flags, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_fs;	.high_level	= 0x02,
	retval = copy_signal(clone_flags, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_sighand;	.high_level	= 0x02,
	retval = copy_mm(clone_flags, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_signal;	.high_level	= 0x02,
	retval = copy_namespaces(clone_flags, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_mm;	.high_level	= 0x02,
	retval = copy_io(clone_flags, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_namespaces;	.high_level	= 0x02,
	retval = copy_thread(clone_flags, stack_start, stack_size, p);	.high_level	= 0x02,
	if (retval)	.high_level	= 0x02,
		goto bad_fork_cleanup_io;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (pid != &init_struct_pid) {	.high_level	= 0x02,
		retval = -ENOMEM;	.high_level	= 0x02,
		pid = alloc_pid(p->nsproxy->pid_ns_for_children);	.high_level	= 0x02,
		if (!pid)	.high_level	= 0x02,
			goto bad_fork_cleanup_io;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	p->set_child_tid = (clone_flags & CLONE_CHILD_SETTID) ? child_tidptr : NULL;	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Clear TID on mm_release()?	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	p->clear_child_tid = (clone_flags & CLONE_CHILD_CLEARTID) ? child_tidptr : NULL;	.high_level	= 0x02,
#ifdef CONFIG_BLOCK	.high_level	= 0x02,
	p->plug = NULL;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
#ifdef CONFIG_FUTEX	.high_level	= 0x02,
	p->robust_list = NULL;	.high_level	= 0x02,
#ifdef CONFIG_COMPAT	.high_level	= 0x02,
	p->compat_robust_list = NULL;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	INIT_LIST_HEAD(&p->pi_state_list);	.high_level	= 0x02,
	p->pi_state_cache = NULL;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * sigaltstack should be cleared when sharing the same VM	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if ((clone_flags & (CLONE_VM|CLONE_VFORK)) == CLONE_VM)	.high_level	= 0x02,
		p->sas_ss_sp = p->sas_ss_size = 0;	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Syscall tracing and stepping should be turned off in the	.high_level	= 0x02,
	 * child regardless of CLONE_PTRACE.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	user_disable_single_step(p);	.high_level	= 0x02,
	clear_tsk_thread_flag(p, TIF_SYSCALL_TRACE);	.high_level	= 0x02,
#ifdef TIF_SYSCALL_EMU	.high_level	= 0x02,
	clear_tsk_thread_flag(p, TIF_SYSCALL_EMU);	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	clear_all_latency_tracing(p);	.high_level	= 0x02,
	.high_level	= 0x02,
	/* ok, now we should be set up.. */	.high_level	= 0x02,
	p->pid = pid_nr(pid);	.high_level	= 0x02,
	if (clone_flags & CLONE_THREAD) {	.high_level	= 0x02,
		p->exit_signal = -1;	.high_level	= 0x02,
		p->group_leader = current->group_leader;	.high_level	= 0x02,
		p->tgid = current->tgid;	.high_level	= 0x02,
	} else {	.high_level	= 0x02,
		if (clone_flags & CLONE_PARENT)	.high_level	= 0x02,
			p->exit_signal = current->group_leader->exit_signal;	.high_level	= 0x02,
		else	.high_level	= 0x02,
			p->exit_signal = (clone_flags & CSIGNAL);	.high_level	= 0x02,
		p->group_leader = p;	.high_level	= 0x02,
		p->tgid = p->pid;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	p->nr_dirtied = 0;	.high_level	= 0x02,
	p->nr_dirtied_pause = 128 >> (PAGE_SHIFT - 10);	.high_level	= 0x02,
	p->dirty_paused_when = 0;	.high_level	= 0x02,
	.high_level	= 0x02,
	p->pdeath_signal = 0;	.high_level	= 0x02,
	INIT_LIST_HEAD(&p->thread_group);	.high_level	= 0x02,
	p->task_works = NULL;	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Make it visible to the rest of the system, but dont wake it up yet.	.high_level	= 0x02,
	 * Need tasklist lock for parent etc handling!	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	write_lock_irq(&tasklist_lock);	.high_level	= 0x02,
	.high_level	= 0x02,
	/* CLONE_PARENT re-uses the old parent */	.high_level	= 0x02,
	if (clone_flags & (CLONE_PARENT|CLONE_THREAD)) {	.high_level	= 0x02,
		p->real_parent = current->real_parent;	.high_level	= 0x02,
		p->parent_exec_id = current->parent_exec_id;	.high_level	= 0x02,
	} else {	.high_level	= 0x02,
		p->real_parent = current;	.high_level	= 0x02,
		p->parent_exec_id = current->self_exec_id;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	spin_lock(&current->sighand->siglock);	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Process group and session signals need to be delivered to just the	.high_level	= 0x02,
	 * parent before the fork or both the parent and the child after the	.high_level	= 0x02,
	 * fork. Restart if a signal comes in before we add the new process to	.high_level	= 0x02,
	 * it's process group.	.high_level	= 0x02,
	 * A fatal signal pending means that current will exit, so the new	.high_level	= 0x02,
	 * thread can't slip out of an OOM kill (or normal SIGKILL).	.high_level	= 0x02,
	*/	.high_level	= 0x02,
	recalc_sigpending();	.high_level	= 0x02,
	if (signal_pending(current)) {	.high_level	= 0x02,
		spin_unlock(&current->sighand->siglock);	.high_level	= 0x02,
		write_unlock_irq(&tasklist_lock);	.high_level	= 0x02,
		retval = -ERESTARTNOINTR;	.high_level	= 0x02,
		goto bad_fork_free_pid;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	if (likely(p->pid)) {	.high_level	= 0x02,
		ptrace_init_task(p, (clone_flags & CLONE_PTRACE) || trace);	.high_level	= 0x02,
	.high_level	= 0x02,
		init_task_pid(p, PIDTYPE_PID, pid);	.high_level	= 0x02,
		if (thread_group_leader(p)) {	.high_level	= 0x02,
			init_task_pid(p, PIDTYPE_PGID, task_pgrp(current));	.high_level	= 0x02,
			init_task_pid(p, PIDTYPE_SID, task_session(current));	.high_level	= 0x02,
	.high_level	= 0x02,
			if (is_child_reaper(pid)) {	.high_level	= 0x02,
				ns_of_pid(pid)->child_reaper = p;	.high_level	= 0x02,
				p->signal->flags |= SIGNAL_UNKILLABLE;	.high_level	= 0x02,
			}	.high_level	= 0x02,
	.high_level	= 0x02,
			p->signal->leader_pid = pid;	.high_level	= 0x02,
			p->signal->tty = tty_kref_get(current->signal->tty);	.high_level	= 0x02,
			list_add_tail(&p->sibling, &p->real_parent->children);	.high_level	= 0x02,
			list_add_tail_rcu(&p->tasks, &init_task.tasks);	.high_level	= 0x02,
			attach_pid(p, PIDTYPE_PGID);	.high_level	= 0x02,
			attach_pid(p, PIDTYPE_SID);	.high_level	= 0x02,
			__this_cpu_inc(process_counts);	.high_level	= 0x02,
		} else {	.high_level	= 0x02,
			current->signal->nr_threads++;	.high_level	= 0x02,
			atomic_inc(&current->signal->live);	.high_level	= 0x02,
			atomic_inc(&current->signal->sigcnt);	.high_level	= 0x02,
			list_add_tail_rcu(&p->thread_group,	.high_level	= 0x02,
					  &p->group_leader->thread_group);	.high_level	= 0x02,
			list_add_tail_rcu(&p->thread_node,	.high_level	= 0x02,
					  &p->signal->thread_head);	.high_level	= 0x02,
		}	.high_level	= 0x02,
		attach_pid(p, PIDTYPE_PID);	.high_level	= 0x02,
		nr_threads++;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	total_forks++;	.high_level	= 0x02,
	spin_unlock(&current->sighand->siglock);	.high_level	= 0x02,
	write_unlock_irq(&tasklist_lock);	.high_level	= 0x02,
	proc_fork_connector(p);	.high_level	= 0x02,
	cgroup_post_fork(p);	.high_level	= 0x02,
	if (clone_flags & CLONE_THREAD)	.high_level	= 0x02,
		threadgroup_change_end(current);	.high_level	= 0x02,
	perf_event_fork(p);	.high_level	= 0x02,
	.high_level	= 0x02,
	trace_task_newtask(p, clone_flags);	.high_level	= 0x02,
	uprobe_copy_process(p, clone_flags);	.high_level	= 0x02,
	.high_level	= 0x02,
	return p;	.high_level	= 0x02,
	.high_level	= 0x02,
bad_fork_free_pid:	.high_level	= 0x02,
	if (pid != &init_struct_pid)	.high_level	= 0x02,
		free_pid(pid);	.high_level	= 0x02,
bad_fork_cleanup_io:	.high_level	= 0x02,
	if (p->io_context)	.high_level	= 0x02,
		exit_io_context(p);	.high_level	= 0x02,
bad_fork_cleanup_namespaces:	.high_level	= 0x02,
	exit_task_namespaces(p);	.high_level	= 0x02,
bad_fork_cleanup_mm:	.high_level	= 0x02,
	if (p->mm)	.high_level	= 0x02,
		mmput(p->mm);	.high_level	= 0x02,
bad_fork_cleanup_signal:	.high_level	= 0x02,
	if (!(clone_flags & CLONE_THREAD))	.high_level	= 0x02,
		free_signal_struct(p->signal);	.high_level	= 0x02,
bad_fork_cleanup_sighand:	.high_level	= 0x02,
	__cleanup_sighand(p->sighand);	.high_level	= 0x02,
bad_fork_cleanup_fs:	.high_level	= 0x02,
	exit_fs(p); /* blocking */	.high_level	= 0x02,
bad_fork_cleanup_files:	.high_level	= 0x02,
	exit_files(p); /* blocking */	.high_level	= 0x02,
bad_fork_cleanup_semundo:	.high_level	= 0x02,
	exit_sem(p);	.high_level	= 0x02,
bad_fork_cleanup_audit:	.high_level	= 0x02,
	audit_free(p);	.high_level	= 0x02,
bad_fork_cleanup_policy:	.high_level	= 0x02,
	perf_event_free_task(p);	.high_level	= 0x02,
#ifdef CONFIG_NUMA	.high_level	= 0x02,
	mpol_put(p->mempolicy);	.high_level	= 0x02,
bad_fork_cleanup_cgroup:	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	if (clone_flags & CLONE_THREAD)	.high_level	= 0x02,
		threadgroup_change_end(current);	.high_level	= 0x02,
	cgroup_exit(p, 0);	.high_level	= 0x02,
	delayacct_tsk_free(p);	.high_level	= 0x02,
	module_put(task_thread_info(p)->exec_domain->module);	.high_level	= 0x02,
bad_fork_cleanup_count:	.high_level	= 0x02,
	atomic_dec(&p->cred->user->processes);	.high_level	= 0x02,
	exit_creds(p);	.high_level	= 0x02,
bad_fork_free:	.high_level	= 0x02,
	free_task(p);	.high_level	= 0x02,
fork_out:	.high_level	= 0x02,
	return ERR_PTR(retval);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
static inline void init_idle_pids(struct pid_link *links)	.high_level	= 0x02,
{	.high_level	= 0x02,
	enum pid_type type;	.high_level	= 0x02,
	.high_level	= 0x02,
	for (type = PIDTYPE_PID; type < PIDTYPE_MAX; ++type) {	.high_level	= 0x02,
		INIT_HLIST_NODE(&links[type].node); /* not really needed */	.high_level	= 0x02,
		links[type].pid = &init_struct_pid;	.high_level	= 0x02,
	}	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
struct task_struct *fork_idle(int cpu)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct task_struct *task;	.high_level	= 0x02,
	task = copy_process(CLONE_VM, 0, 0, NULL, &init_struct_pid, 0);	.high_level	= 0x02,
	if (!IS_ERR(task)) {	.high_level	= 0x02,
		init_idle_pids(task->pids);	.high_level	= 0x02,
		init_idle(task, cpu);	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	return task;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 *  Ok, this is the main fork-routine.	.high_level	= 0x02,
 *	.high_level	= 0x02,
 * It copies the process, and if successful kick-starts	.high_level	= 0x02,
 * it and waits for it to finish using the VM if required.	.high_level	= 0x02,
 */	.high_level	= 0x02,
long do_fork(unsigned long clone_flags,	.high_level	= 0x02,
	      unsigned long stack_start,	.high_level	= 0x02,
	      unsigned long stack_size,	.high_level	= 0x02,
	      int __user *parent_tidptr,	.high_level	= 0x02,
	      int __user *child_tidptr)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct task_struct *p;	.high_level	= 0x02,
	int trace = 0;	.high_level	= 0x02,
	long nr;	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Determine whether and which event to report to ptracer.  When	.high_level	= 0x02,
	 * called from kernel_thread or CLONE_UNTRACED is explicitly	.high_level	= 0x02,
	 * requested, no event is reported; otherwise, report if the event	.high_level	= 0x02,
	 * for the type of forking is enabled.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (!(clone_flags & CLONE_UNTRACED)) {	.high_level	= 0x02,
		if (clone_flags & CLONE_VFORK)	.high_level	= 0x02,
			trace = PTRACE_EVENT_VFORK;	.high_level	= 0x02,
		else if ((clone_flags & CSIGNAL) != SIGCHLD)	.high_level	= 0x02,
			trace = PTRACE_EVENT_CLONE;	.high_level	= 0x02,
		else	.high_level	= 0x02,
			trace = PTRACE_EVENT_FORK;	.high_level	= 0x02,
	.high_level	= 0x02,
		if (likely(!ptrace_event_enabled(current, trace)))	.high_level	= 0x02,
			trace = 0;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	p = copy_process(clone_flags, stack_start, stack_size,	.high_level	= 0x02,
			 child_tidptr, NULL, trace);	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Do this prior waking up the new thread - the thread pointer	.high_level	= 0x02,
	 * might get invalid after that point, if the thread exits quickly.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (!IS_ERR(p)) {	.high_level	= 0x02,
		struct completion vfork;	.high_level	= 0x02,
	.high_level	= 0x02,
		trace_sched_process_fork(current, p);	.high_level	= 0x02,
	.high_level	= 0x02,
		nr = task_pid_vnr(p);	.high_level	= 0x02,
	.high_level	= 0x02,
		if (clone_flags & CLONE_PARENT_SETTID)	.high_level	= 0x02,
			put_user(nr, parent_tidptr);	.high_level	= 0x02,
	.high_level	= 0x02,
		if (clone_flags & CLONE_VFORK) {	.high_level	= 0x02,
			p->vfork_done = &vfork;	.high_level	= 0x02,
			init_completion(&vfork);	.high_level	= 0x02,
			get_task_struct(p);	.high_level	= 0x02,
		}	.high_level	= 0x02,
	.high_level	= 0x02,
		wake_up_new_task(p);	.high_level	= 0x02,
	.high_level	= 0x02,
		/* forking complete and child started to run, tell ptracer */	.high_level	= 0x02,
		if (unlikely(trace))	.high_level	= 0x02,
			ptrace_event(trace, nr);	.high_level	= 0x02,
	.high_level	= 0x02,
		if (clone_flags & CLONE_VFORK) {	.high_level	= 0x02,
			if (!wait_for_vfork_done(p, &vfork))	.high_level	= 0x02,
				ptrace_event(PTRACE_EVENT_VFORK_DONE, nr);	.high_level	= 0x02,
		}	.high_level	= 0x02,
	} else {	.high_level	= 0x02,
		nr = PTR_ERR(p);	.high_level	= 0x02,
	}	.high_level	= 0x02,
	return nr;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Create a kernel thread.	.high_level	= 0x02,
 */	.high_level	= 0x02,
pid_t kernel_thread(int (*fn)(void *), void *arg, unsigned long flags)	.high_level	= 0x02,
{	.high_level	= 0x02,
	return do_fork(flags|CLONE_VM|CLONE_UNTRACED, (unsigned long)fn,	.high_level	= 0x02,
		(unsigned long)arg, NULL, NULL);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef __ARCH_WANT_SYS_FORK	.high_level	= 0x02,
SYSCALL_DEFINE0(fork)	.high_level	= 0x02,
{	.high_level	= 0x02,
#ifdef CONFIG_MMU	.high_level	= 0x02,
	return do_fork(SIGCHLD, 0, 0, NULL, NULL);	.high_level	= 0x02,
#else	.high_level	= 0x02,
	/* can not support in nommu mode */	.high_level	= 0x02,
	return -EINVAL;	.high_level	= 0x02,
#endif	.high_level	= 0x02,
}	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef __ARCH_WANT_SYS_VFORK	.high_level	= 0x02,
SYSCALL_DEFINE0(vfork)	.high_level	= 0x02,
{	.high_level	= 0x02,
	return do_fork(CLONE_VFORK | CLONE_VM | SIGCHLD, 0,	.high_level	= 0x02,
			0, NULL, NULL);	.high_level	= 0x02,
}	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
#ifdef __ARCH_WANT_SYS_CLONE	.high_level	= 0x02,
#ifdef CONFIG_CLONE_BACKWARDS	.high_level	= 0x02,
SYSCALL_DEFINE5(clone, unsigned long, clone_flags, unsigned long, newsp,	.high_level	= 0x02,
		 int __user *, parent_tidptr,	.high_level	= 0x02,
		 int, tls_val,	.high_level	= 0x02,
		 int __user *, child_tidptr)	.high_level	= 0x02,
#elif defined(CONFIG_CLONE_BACKWARDS2)	.high_level	= 0x02,
SYSCALL_DEFINE5(clone, unsigned long, newsp, unsigned long, clone_flags,	.high_level	= 0x02,
		 int __user *, parent_tidptr,	.high_level	= 0x02,
		 int __user *, child_tidptr,	.high_level	= 0x02,
		 int, tls_val)	.high_level	= 0x02,
#elif defined(CONFIG_CLONE_BACKWARDS3)	.high_level	= 0x02,
SYSCALL_DEFINE6(clone, unsigned long, clone_flags, unsigned long, newsp,	.high_level	= 0x02,
		int, stack_size,	.high_level	= 0x02,
		int __user *, parent_tidptr,	.high_level	= 0x02,
		int __user *, child_tidptr,	.high_level	= 0x02,
		int, tls_val)	.high_level	= 0x02,
#else	.high_level	= 0x02,
SYSCALL_DEFINE5(clone, unsigned long, clone_flags, unsigned long, newsp,	.high_level	= 0x02,
		 int __user *, parent_tidptr,	.high_level	= 0x02,
		 int __user *, child_tidptr,	.high_level	= 0x02,
		 int, tls_val)	.high_level	= 0x02,
#endif	.high_level	= 0x02,
{	.high_level	= 0x02,
	return do_fork(clone_flags, newsp, 0, parent_tidptr, child_tidptr);	.high_level	= 0x02,
}	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
#ifndef ARCH_MIN_MMSTRUCT_ALIGN	.high_level	= 0x02,
#define ARCH_MIN_MMSTRUCT_ALIGN 0	.high_level	= 0x02,
#endif	.high_level	= 0x02,
	.high_level	= 0x02,
static void sighand_ctor(void *data)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct sighand_struct *sighand = data;	.high_level	= 0x02,
	.high_level	= 0x02,
	spin_lock_init(&sighand->siglock);	.high_level	= 0x02,
	init_waitqueue_head(&sighand->signalfd_wqh);	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
void __init proc_caches_init(void)	.high_level	= 0x02,
{	.high_level	= 0x02,
	sighand_cachep = kmem_cache_create("sighand_cache",	.high_level	= 0x02,
			sizeof(struct sighand_struct), 0,	.high_level	= 0x02,
			SLAB_HWCACHE_ALIGN|SLAB_PANIC|SLAB_DESTROY_BY_RCU|	.high_level	= 0x02,
			SLAB_NOTRACK, sighand_ctor);	.high_level	= 0x02,
	signal_cachep = kmem_cache_create("signal_cache",	.high_level	= 0x02,
			sizeof(struct signal_struct), 0,	.high_level	= 0x02,
			SLAB_HWCACHE_ALIGN|SLAB_PANIC|SLAB_NOTRACK, NULL);	.high_level	= 0x02,
	files_cachep = kmem_cache_create("files_cache",	.high_level	= 0x02,
			sizeof(struct files_struct), 0,	.high_level	= 0x02,
			SLAB_HWCACHE_ALIGN|SLAB_PANIC|SLAB_NOTRACK, NULL);	.high_level	= 0x02,
	fs_cachep = kmem_cache_create("fs_cache",	.high_level	= 0x02,
			sizeof(struct fs_struct), 0,	.high_level	= 0x02,
			SLAB_HWCACHE_ALIGN|SLAB_PANIC|SLAB_NOTRACK, NULL);	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * FIXME! The "sizeof(struct mm_struct)" currently includes the	.high_level	= 0x02,
	 * whole struct cpumask for the OFFSTACK case. We could change	.high_level	= 0x02,
	 * this to *only* allocate as much of it as required by the	.high_level	= 0x02,
	 * maximum number of CPU's we can ever have.  The cpumask_allocation	.high_level	= 0x02,
	 * is at the end of the structure, exactly for that reason.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	mm_cachep = kmem_cache_create("mm_struct",	.high_level	= 0x02,
			sizeof(struct mm_struct), ARCH_MIN_MMSTRUCT_ALIGN,	.high_level	= 0x02,
			SLAB_HWCACHE_ALIGN|SLAB_PANIC|SLAB_NOTRACK, NULL);	.high_level	= 0x02,
	vm_area_cachep = KMEM_CACHE(vm_area_struct, SLAB_PANIC);	.high_level	= 0x02,
	mmap_init();	.high_level	= 0x02,
	nsproxy_cache_init();	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Check constraints on flags passed to the unshare system call.	.high_level	= 0x02,
 */	.high_level	= 0x02,
static int check_unshare_flags(unsigned long unshare_flags)	.high_level	= 0x02,
{	.high_level	= 0x02,
	if (unshare_flags & ~(CLONE_THREAD|CLONE_FS|CLONE_NEWNS|CLONE_SIGHAND|	.high_level	= 0x02,
				CLONE_VM|CLONE_FILES|CLONE_SYSVSEM|	.high_level	= 0x02,
				CLONE_NEWUTS|CLONE_NEWIPC|CLONE_NEWNET|	.high_level	= 0x02,
				CLONE_NEWUSER|CLONE_NEWPID))	.high_level	= 0x02,
		return -EINVAL;	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * Not implemented, but pretend it works if there is nothing to	.high_level	= 0x02,
	 * unshare. Note that unsharing CLONE_THREAD or CLONE_SIGHAND	.high_level	= 0x02,
	 * needs to unshare vm.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (unshare_flags & (CLONE_THREAD | CLONE_SIGHAND | CLONE_VM)) {	.high_level	= 0x02,
		/* FIXME: get_task_mm() increments ->mm_users */	.high_level	= 0x02,
		if (atomic_read(&current->mm->mm_users) > 1)	.high_level	= 0x02,
			return -EINVAL;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Unshare the filesystem structure if it is being shared	.high_level	= 0x02,
 */	.high_level	= 0x02,
static int unshare_fs(unsigned long unshare_flags, struct fs_struct **new_fsp)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct fs_struct *fs = current->fs;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (!(unshare_flags & CLONE_FS) || !fs)	.high_level	= 0x02,
		return 0;	.high_level	= 0x02,
	.high_level	= 0x02,
	/* don't need lock here; in the worst case we'll do useless copy */	.high_level	= 0x02,
	if (fs->users == 1)	.high_level	= 0x02,
		return 0;	.high_level	= 0x02,
	.high_level	= 0x02,
	*new_fsp = copy_fs_struct(fs);	.high_level	= 0x02,
	if (!*new_fsp)	.high_level	= 0x02,
		return -ENOMEM;	.high_level	= 0x02,
	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * Unshare file descriptor table if it is being shared	.high_level	= 0x02,
 */	.high_level	= 0x02,
static int unshare_fd(unsigned long unshare_flags, struct files_struct **new_fdp)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct files_struct *fd = current->files;	.high_level	= 0x02,
	int error = 0;	.high_level	= 0x02,
	.high_level	= 0x02,
	if ((unshare_flags & CLONE_FILES) &&	.high_level	= 0x02,
	    (fd && atomic_read(&fd->count) > 1)) {	.high_level	= 0x02,
		*new_fdp = dup_fd(fd, &error);	.high_level	= 0x02,
		if (!*new_fdp)	.high_level	= 0x02,
			return error;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 * unshare allows a process to 'unshare' part of the process	.high_level	= 0x02,
 * context which was originally shared using clone.  copy_*	.high_level	= 0x02,
 * functions used by do_fork() cannot be used here directly	.high_level	= 0x02,
 * because they modify an inactive task_struct that is being	.high_level	= 0x02,
 * constructed. Here we are modifying the current, active,	.high_level	= 0x02,
 * task_struct.	.high_level	= 0x02,
 */	.high_level	= 0x02,
SYSCALL_DEFINE1(unshare, unsigned long, unshare_flags)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct fs_struct *fs, *new_fs = NULL;	.high_level	= 0x02,
	struct files_struct *fd, *new_fd = NULL;	.high_level	= 0x02,
	struct cred *new_cred = NULL;	.high_level	= 0x02,
	struct nsproxy *new_nsproxy = NULL;	.high_level	= 0x02,
	int do_sysvsem = 0;	.high_level	= 0x02,
	int err;	.high_level	= 0x02,
	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * If unsharing a user namespace must also unshare the thread.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (unshare_flags & CLONE_NEWUSER)	.high_level	= 0x02,
		unshare_flags |= CLONE_THREAD | CLONE_FS;	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * If unsharing a thread from a thread group, must also unshare vm.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (unshare_flags & CLONE_THREAD)	.high_level	= 0x02,
		unshare_flags |= CLONE_VM;	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * If unsharing vm, must also unshare signal handlers.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (unshare_flags & CLONE_VM)	.high_level	= 0x02,
		unshare_flags |= CLONE_SIGHAND;	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * If unsharing namespace, must also unshare filesystem information.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (unshare_flags & CLONE_NEWNS)	.high_level	= 0x02,
		unshare_flags |= CLONE_FS;	.high_level	= 0x02,
	.high_level	= 0x02,
	err = check_unshare_flags(unshare_flags);	.high_level	= 0x02,
	if (err)	.high_level	= 0x02,
		goto bad_unshare_out;	.high_level	= 0x02,
	/*	.high_level	= 0x02,
	 * CLONE_NEWIPC must also detach from the undolist: after switching	.high_level	= 0x02,
	 * to a new ipc namespace, the semaphore arrays from the old	.high_level	= 0x02,
	 * namespace are unreachable.	.high_level	= 0x02,
	 */	.high_level	= 0x02,
	if (unshare_flags & (CLONE_NEWIPC|CLONE_SYSVSEM))	.high_level	= 0x02,
		do_sysvsem = 1;	.high_level	= 0x02,
	err = unshare_fs(unshare_flags, &new_fs);	.high_level	= 0x02,
	if (err)	.high_level	= 0x02,
		goto bad_unshare_out;	.high_level	= 0x02,
	err = unshare_fd(unshare_flags, &new_fd);	.high_level	= 0x02,
	if (err)	.high_level	= 0x02,
		goto bad_unshare_cleanup_fs;	.high_level	= 0x02,
	err = unshare_userns(unshare_flags, &new_cred);	.high_level	= 0x02,
	if (err)	.high_level	= 0x02,
		goto bad_unshare_cleanup_fd;	.high_level	= 0x02,
	err = unshare_nsproxy_namespaces(unshare_flags, &new_nsproxy,	.high_level	= 0x02,
					 new_cred, new_fs);	.high_level	= 0x02,
	if (err)	.high_level	= 0x02,
		goto bad_unshare_cleanup_cred;	.high_level	= 0x02,
	.high_level	= 0x02,
	if (new_fs || new_fd || do_sysvsem || new_cred || new_nsproxy) {	.high_level	= 0x02,
		if (do_sysvsem) {	.high_level	= 0x02,
			/*	.high_level	= 0x02,
			 * CLONE_SYSVSEM is equivalent to sys_exit().	.high_level	= 0x02,
			 */	.high_level	= 0x02,
			exit_sem(current);	.high_level	= 0x02,
		}	.high_level	= 0x02,
	.high_level	= 0x02,
		if (new_nsproxy)	.high_level	= 0x02,
			switch_task_namespaces(current, new_nsproxy);	.high_level	= 0x02,
	.high_level	= 0x02,
		task_lock(current);	.high_level	= 0x02,
	.high_level	= 0x02,
		if (new_fs) {	.high_level	= 0x02,
			fs = current->fs;	.high_level	= 0x02,
			spin_lock(&fs->lock);	.high_level	= 0x02,
			current->fs = new_fs;	.high_level	= 0x02,
			if (--fs->users)	.high_level	= 0x02,
				new_fs = NULL;	.high_level	= 0x02,
			else	.high_level	= 0x02,
				new_fs = fs;	.high_level	= 0x02,
			spin_unlock(&fs->lock);	.high_level	= 0x02,
		}	.high_level	= 0x02,
	.high_level	= 0x02,
		if (new_fd) {	.high_level	= 0x02,
			fd = current->files;	.high_level	= 0x02,
			current->files = new_fd;	.high_level	= 0x02,
			new_fd = fd;	.high_level	= 0x02,
		}	.high_level	= 0x02,
	.high_level	= 0x02,
		task_unlock(current);	.high_level	= 0x02,
	.high_level	= 0x02,
		if (new_cred) {	.high_level	= 0x02,
			/* Install the new user namespace */	.high_level	= 0x02,
			commit_creds(new_cred);	.high_level	= 0x02,
			new_cred = NULL;	.high_level	= 0x02,
		}	.high_level	= 0x02,
	}	.high_level	= 0x02,
	.high_level	= 0x02,
bad_unshare_cleanup_cred:	.high_level	= 0x02,
	if (new_cred)	.high_level	= 0x02,
		put_cred(new_cred);	.high_level	= 0x02,
bad_unshare_cleanup_fd:	.high_level	= 0x02,
	if (new_fd)	.high_level	= 0x02,
		put_files_struct(new_fd);	.high_level	= 0x02,
	.high_level	= 0x02,
bad_unshare_cleanup_fs:	.high_level	= 0x02,
	if (new_fs)	.high_level	= 0x02,
		free_fs_struct(new_fs);	.high_level	= 0x02,
	.high_level	= 0x02,
bad_unshare_out:	.high_level	= 0x02,
	return err;	.high_level	= 0x02,
}	.high_level	= 0x02,
	.high_level	= 0x02,
/*	.high_level	= 0x02,
 *	Helper to unshare the files of the current task.	.high_level	= 0x02,
 *	We don't want to expose copy_files internals to	.high_level	= 0x02,
 *	the exec layer of the kernel.	.high_level	= 0x02,
 */	.high_level	= 0x02,
	.high_level	= 0x02,
int unshare_files(struct files_struct **displaced)	.high_level	= 0x02,
{	.high_level	= 0x02,
	struct task_struct *task = current;	.high_level	= 0x02,
	struct files_struct *copy = NULL;	.high_level	= 0x02,
	int error;	.high_level	= 0x02,
	.high_level	= 0x02,
	error = unshare_fd(CLONE_FILES, &copy);	.high_level	= 0x02,
	if (error || !copy) {	.high_level	= 0x02,
		*displaced = NULL;	.high_level	= 0x02,
		return error;	.high_level	= 0x02,
	}	.high_level	= 0x02,
	*displaced = task->files;	.high_level	= 0x02,
	task_lock(task);	.high_level	= 0x02,
	task->files = copy;	.high_level	= 0x02,
	task_unlock(task);	.high_level	= 0x02,
	return 0;	.high_level	= 0x02,
}